postgres:
  username: kyuber
  password: 0609
  host: localhost
  port: 5432
  dbname: traccar_db
  trigger:
    name: traccar_db
    table: tc_positions
    channel: channel
    timeout: 5
  store:
    name: traccar_db
    table: staypoints
    channel: channel
    timeout: 1000


mongo:
  mongo:
  username: kyuber
  password: 0609
  host: localhost
  port: 27017
  dbname: hyu_staypoint

naver:
  client_id: o8qps7du4b
  client_secret: 2PPiE2NgOPp9YkBaip0nPgTxrbBo0mioYjy8lY0r